#!/usr/bin/env bash

# activate the environment
source activate snakemake_env2 || conda activate snakemake_env2
if [ $# -eq 0 ];then
	seq2geno_gui
else
	seq2geno.py $@
fi
source deactivate || conda deactivate

